server:
  port: 2000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/

spring:
  application:
    name: dzc-crowd-mysql
  datasource:
    name: mydb
    url: jdbc:mysql://127.0.0.1:3306/project_crowd?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: 'root'
    password: '123456'

mybatis:
  mapper-locations: classpath*:/mybatis/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.dzc.crowd.mapper: debug
    com.dzc.crowd.test: debug

