server:
  port: 7000
spring:
  application:
    name: dzc-crowd-pay
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.154.101
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

ali:
  pay:
    appId: 2021000116667467
    merchantPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCRSshrkx8lJFXmVZ2nsK5IfSWtjXQXO2P4UGDZcLhmYs2gWFwJYxlBXmnOU+GF/Fayq0CibvcrRRYoQTNTYaZm3KsluvJ8D+STIkPHPLW15vcNwvMVY7iNa0T2iVL0q4lYGthIJMVwTOhL8CaU1ZqA+I3KX/ruS27isVdG89UD94WVY04gyetThhxDkXmBtqZXK75pbUOteIVhBodR+ICtTZ5MVqJsP/xeruBBurO6sDmNiNJeJCSXnYUKk1zl0u2T4W2PFISV+48HJ7PwpSbAeHYnPes1l3qD943gqaW6qsutjUz6dsdcEvr6Pvl+BrxmWvQvksO0S3xdNyHBdlL3AgMBAAECggEAX6TBBr/UstiWi4g0vlz6fdGUaglCMMDx8FbJSpp/aTcFcdZ4z90ilPuX3zEsts0ELZ26cLNnll5mVZ2GMg+IQRJmv/GvCqhTqd/WimOWouYmIDMDXkNFDCNfRIPlzhbV1N/nHKbIKkMWcFborvVmPhxhCqXgQ9n4ZtajQ5vj0DW1AMuX4jQTgmc2zZftR78MexT0PUFstPbyuLJAtC5U6ky1tM/Wcm2qkcqrLex4r6MrYgkFT246qARgzvsVjofm3Hlvu2t4Vj37oTKibwROMxIOtBhyzrUurjshTF8S27AibKlXKy1cWyESj4dJCaogXcdXuY4/8u3FZioRj+4IYQKBgQDGQeZmuW5IHkGWEoTAdUAoFcIEDOttR1Z/Tkk/ceFwcnhABis5upVGGO0yC9oNcGQ/ik3zBUSOAXcgXHiqBo4wS+ehmabPP1PNuav7JM90LaHaxDVNUIEk/aR6oAz5/dOeMOO1vcN0fen60U8jViVrvMLFikO3cQcGz3VgXpEvOQKBgQC7m8htLbptX3oivBmnTuumjshObzmD8339Mr2zHzh29ypjl/0hBdsypmyYN0eum+B11X03nfhqRU/2E33NrAC9lmV1xQ9oizQ2CgBh1MdXmU4ClpSak6+oWnxs5IodPJRZeeMFHixjxsi1Dpde5xM7FmBV2gB8cSNYm8yy+pRjrwKBgBzChIzUS3Y0xWjiyNUubR8jgOCbiy9wENEo5yFIAN8SC/Wlr3GRaoQfq5D9/STD8Bbzljkxw28iMUjFgU+Q4eGJsVFU+8jGs/5898DX5yxATmFw4xaTHhjinpCXVSqSsrcY+n9rxsXIWj/jSyqiHY2SdWK4mvgqck1/nNRdA4ypAoGBAKZcry95pF6GkuSoTktZpYfOB3veD2+eBPP5AdUL82MzLEiip5mX+teAUr3sD0mb+kAjb2VZVMbP7ec1Q5KVWxbDffcgJti60DK3Tb1zFM3uKQoMg3xLSDIPA1UAmCTy6k4p0pFgP1a/GI3NgZdra1czMXwP0+yF2yUhCzUPFXULAoGAWdJVALl8MfbDwRaZGxBZvb1jqGpuarCdfN4hJA9psxjKt3kU8wAOKjA4Ftz8HX/vRR9DdCAL+TZF77bVwL/ffOwG1ThdVBf5R2sILSYvebVOeP6GCsk2VHsDpS2REp3XIDpwJlM3sJ/ElynTq9QBeoiyXTlIRpYbhgMatHEHhK8=
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA55T2i2kVXwyQWHvE+RmRC08qay4Q6BZ63jh21lua/7/+qM7cagG3D5yyXU0KMyLCePlc5zHpz2ZMpFKStEZrZwHg7lzbv14N6lQ4p3rCUFPGkFN9xmQoBhtd66Y/XFDPq2AQ2uSBMs6dyU7pjGhUc7GW3MDcNfPhFvrINA0YiwkqJYubne7+sf1CsZ24rctKunx+OT02p8xIwIhGFwoVkMG1+sCRPt+GwPE2ZO15JL9Q96SIZzwoKWAp7hMKCrvsDU7KVk9nfOVExh5g7UBmJTBN+RlMrcoDbq/748jS5tmJUKcQn5hJIc8xOsMp1UfdicdQrtAJHXk/vp+yjpRHIQIDAQAB
    notifyUrl: http://kx9t76.natappfree.cc/pay/notify
    returnUrl: http://localhost:8081/pay/return
    signType: RSA2
    charset: utf-8
    gatewayUrl: https://openapi.alipaydev.com/gateway.do

