server:
  port: 4000
spring:
  application:
    name: dzc-crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.154.101
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
short:
  message:
    host: https://zwp.market.alicloudapi.com
    path: /sms/sendv2
    method: GET
    appcode: c959674907484fab84c1f8d87c943329

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
