aliyun:
  oss:
    endPoint: http://oss-cn-beijing.aliyuncs.com
    bucketName: crowdfunding-dzc
    accessKeyId: LTAI4GF2S2S6KK6h9pyjhEtz
    accessKeySecret: C1DartUYaBDhmNH9ZBLJdAYkU914Zp
    bucketDomain: http://crowdfunding-dzc.oss-cn-beijing.aliyuncs.com

spring:
  application:
    name: dzc-crowd-project
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
  redis:
    host: 192.168.154.101
  session:
    store-type: redis

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/

server:
  port: 5000